### ISSUE TITLE
Bolt: weird typos in the "Secrets Management with Vault" docs

### ISSUE THREAD

**Issue by ji-podhead** [puppetlabs/puppet-docs#1169]
https://www.puppet.com/integrations/vault-by-hashicorp
this says:
```yaml
plugins:
  vault:
    server_url: https://vault.example.com:8200cacert: /path/to/caauth:
      method: tokentoken: xxxxx-xxxxx
```
i think this should be similar to this:

```yaml
# /etc/puppetlabs/bolt/bolt-defaults.yaml
plugins:
  aws_inventory:
    credentials: /etc/aws/credentials
  vault:
    server_url: http://example.com
    auth:
      method: token
      token: xxxx-xxxx-xxxx-xxxx
```
 https://www.puppet.com/docs/bolt/latest/configuring_bolt.html
      
      
  also is there any tutorial/ comprehensive guide on how to start a normal project without docker?
  i wanna use puppet along with terraform and github actions. its really hard to get started, nobody on discord can help me and i really asked in almost any devops, k8s and networking channel. I really just dont know how to get started
